# Generated by Django 4.0.5 on 2022-06-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occupant_name', models.CharField(max_length=100)),
                ('occupant_email', models.EmailField(max_length=254)),
                ('occupant_occupation', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_nights', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
